---
- hosts: all
  become: yes
  tasks:
  - name: Add the user
    user:
      name: demo
      shell: /bin/bash
      append: yes

  - name: create the dir
    file:
      path: /home/vagrant/task
      state: directory
      mode: 0775   
      owner: vagrant
      group: vagrant

  - name: Get the code
    become: vagrant
    git:
      repo: https://github.com/srmanikandan/zerodha_task.git
      dest: /home/vagrant/task
      update: no

  - name: configure system settings, file descriptors and number of threads
    pam_limits:
      domain: demo
      limit_type: "{{item.limit_type}}"
      limit_item: "{{item.limit_item}}"
      value: "{{item.value}}"
    with_items:
      - { limit_type: '-', limit_item: 'nofile', value: 65536 }
      - { limit_type: '-', limit_item: 'nproc', value: 65536 }
      - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
      - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }

  - name: Install aptitude using apt
    become: yes
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    become: yes
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: yes
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    become: yes
    apt: update_cache=yes name=docker-ce state=latest

  - name: Ensure docker-compose is installed and available
    shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

  - name: start all
    become: yes
    command: docker-compose -f /home/vagrant/task/docker-compose.yml up -d
                              